sensor_msgs/Image image_rgb
sensor_msgs/Image image_depth
sensor_msgs/CameraInfo camera_info
bool is_right_side # Whether to give the RIGHT side of the lane (true) or LEFT side of the lane (false)
---
geometry_msgs/PointStamped start_point # Start is considered the CLOSEST 3D point to the camera
geometry_msgs/PointStamped end_point # End is considered the FARTHEST 3D point to the camera
bool success
